/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsv.register.view;

import qlsv.register.controller.LoginController;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author MAY 09
 */
public class OptionView extends javax.swing.JFrame {

    /**
     * Creates new form SubjectView
     */
    public OptionView() {
        initComponents();
        this.setTitle("Cửa sổ lựa chọn");
        this.setLocationRelativeTo(null);
        
        ImageIcon icon = new ImageIcon("logo\\logo.png");
//        ImageIcon icon = new ImageIcon("src\\main\\resources\\img\\logo.png");
        setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ButtonSubject = new button.MyButton();
        ButtonStudent = new button.MyButton();
        ButtonRegister = new button.MyButton();
        ButtonStatistics = new button.MyButton();
        LogoutButton = new javax.swing.JLabel();
        BackGroundOption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);

        ButtonSubject.setBorder(null);
        ButtonSubject.setText("Quản lý học phần");
        ButtonSubject.setRadius(90);

        ButtonStudent.setBorder(null);
        ButtonStudent.setText("Quản lý sinh viên");
        ButtonStudent.setRadius(90);

        ButtonRegister.setBorder(null);
        ButtonRegister.setText("Đăng ký môn học");
        ButtonRegister.setRadius(90);

        ButtonStatistics.setBorder(null);
        ButtonStatistics.setText("Thống kê");
        ButtonStatistics.setRadius(90);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonSubject, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
            .addComponent(ButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ButtonStatistics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ButtonStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(ButtonSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(ButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ButtonStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        ButtonSubject.setFont(new java.awt.Font("Cambria", 1, 24));
        ButtonStudent.setFont(new java.awt.Font("Cambria", 1, 24));
        ButtonRegister.setFont(new java.awt.Font("Cambria", 1, 24));
        ButtonStatistics.setFont(new java.awt.Font("Cambria", 1, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, 450, 430));

        LogoutButton.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Đăng xuất");
        LogoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutButtonMouseExited(evt);
            }
        });
        getContentPane().add(LogoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 20, 80, 20));

        BackGroundOption.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/option3.jpg"))); // NOI18N
        getContentPane().add(BackGroundOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseClicked
        LoginView loginView = new LoginView();
        LoginController loginController = new LoginController(loginView);
        loginController.showLoginView();
        setVisible(false);
    }//GEN-LAST:event_LogoutButtonMouseClicked

    private void LogoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseEntered
        LogoutButton.setForeground(new Color(204, 0, 0));
    }//GEN-LAST:event_LogoutButtonMouseEntered

    private void LogoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutButtonMouseExited
        LogoutButton.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_LogoutButtonMouseExited

    public void addSubjectListener(ActionListener listener) {
        ButtonSubject.addActionListener(listener);
    }
    
    public void addStudentListener(ActionListener listener) {
        ButtonStudent.addActionListener(listener);
    }
    
    public void addRegisterListener(ActionListener listener) {
        ButtonRegister.addActionListener(listener);
    }
    
    public void addStatisticsListener(ActionListener listener) {
        ButtonStatistics.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGroundOption;
    private button.MyButton ButtonRegister;
    private button.MyButton ButtonStatistics;
    private button.MyButton ButtonStudent;
    private button.MyButton ButtonSubject;
    private javax.swing.JLabel LogoutButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
